on:
  pull_request:
    branches:
      - master
name: Pull request workflow
jobs: 
  validate_markets:
    name: Validate Featured Markets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Node-js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - name: Install Dependencies
        run: yarn install --ignore-engines # will run `yarn install` command

      - name: Validate featured markets schema
        run: yarn validate # validate using json schema
      
      - name: Test market entries for invalid/duplicate markets
        run: yarn check-configs mainnet testnet devnet # check using check_configs.ts script